version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      - APP_ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=on_call_duty_planner
      - DB_USER=app_user
      - DB_PASSWORD=secure_password

  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=on_call_duty_planner
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=secure_password

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - /var/opt/pgbackups:/backups
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=on_call_duty_planner
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=secure_password
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge
