version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      - APP_ENV=production
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=on_call_duty_planner
      - DB_USER=app_user
      - DB_PASSWORD=secure_password
    networks:
      app_network:
        aliases:
          - web

  database:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_DATABASE=on_call_duty_planner
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=secure_password
      - MYSQL_ROOT_PASSWORD=root_secure_password
    ports:
      - "3306:3306"
    networks:
      app_network:
        aliases:
          - mysql
          - database

  backup:
    image: fradelg/mysql-cron-backup
    restart: always
    volumes:
      - /mnt/datadisk/backup:/backups
    depends_on:
      - database
    environment:
      - DB_DUMP_TARGET=/backups
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=2300
      - DB_USER=app_user
      - DB_PASS=secure_password
      - DB_SERVER=database
    networks:
      app_network:
        aliases:
          - backup

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      app_network:
        aliases:
          - redis

volumes:
  mysql_data:
  redis_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
