version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      - APP_ENV=production
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=on_call_duty_planner
      - DB_USER=app_user
      - DB_PASSWORD=secure_password

  database:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_DATABASE=on_call_duty_planner
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=secure_password
      - MYSQL_ROOT_PASSWORD=root_secure_password
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  backup:
    image: fradelg/mysql-cron-backup
    restart: always
    volumes:
      - /var/opt/mysqlbackups:/backups
    depends_on:
      - database
    environment:
      - DB_DUMP_TARGET=/backups
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=2300
      - DB_USER=app_user
      - DB_PASS=secure_password
      - DB_SERVER=database

volumes:
  mysql_data:
  redis_data:

networks:
  default:
    driver: bridge
